// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCGPrzRYked251nsutWo1DeevoP-Gs6yPY',
    appId: '1:847105340152:web:7cf7262f592a303ba9010d',
    messagingSenderId: '847105340152',
    projectId: 'flutterotp4124',
    authDomain: 'flutterotp4124.firebaseapp.com',
    storageBucket: 'flutterotp4124.appspot.com',
    measurementId: 'G-X535KYYMD8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD07Pbjl0-83oVLPs8c7XDeDhXeBrGjQLc',
    appId: '1:847105340152:android:3c23fa1afe397627a9010d',
    messagingSenderId: '847105340152',
    projectId: 'flutterotp4124',
    storageBucket: 'flutterotp4124.appspot.com',
  );
}
